MDomain linkedcode.com www.linkedcode.com auth.linkedcode.com

# linkedcode.com → www (HTTP)
<VirtualHost *:80>
    ServerName linkedcode.com
    ServerAlias www.linkedcode.com
    ErrorLog /var/www/linkedcode/logs/error.log
    CustomLog /var/www/linkedcode/logs/access.log combined
    RewriteEngine On
    RewriteRule ^ https://www.linkedcode.com%{REQUEST_URI} [R=301,L]
</VirtualHost>

# auth.linkedcode.com (HTTP)
<VirtualHost *:80>
    ServerName auth.linkedcode.com
    ErrorLog /var/www/linkedcode/logs/error.log
    CustomLog /var/www/linkedcode/logs/access.log combined
    RewriteEngine On
    RewriteRule ^ https://auth.linkedcode.com%{REQUEST_URI} [R=301,L]
</VirtualHost>

# linkedcode.com → www (HTTPS)
<VirtualHost *:443>
    ServerName linkedcode.com
    ErrorLog /var/www/linkedcode/logs/error.log
    CustomLog /var/www/linkedcode/logs/access.log combined
    SSLEngine On
    RewriteEngine On
    RewriteRule ^ https://www.linkedcode.com%{REQUEST_URI} [R=301,L]
</VirtualHost>

# www.linkedcode.com (HTTPS)
<VirtualHost *:443>
    ServerName www.linkedcode.com
    ErrorLog /var/www/linkedcode/logs/error.log
    CustomLog /var/www/linkedcode/logs/access.log combined
    SSLEngine On
    ProxyPreserveHost On
    ProxyPass / http://linkedcode-www/
    ProxyPassReverse / http://linkedcode-www/
</VirtualHost>

# auth.linkedcode.com (HTTPS)
<VirtualHost *:443>
    ServerName auth.linkedcode.com
    ErrorLog /var/www/linkedcode/logs/error.log
    CustomLog /var/www/linkedcode/logs/access.log combined
    SSLEngine On
    ProxyPreserveHost On
    ProxyPass / http://linkedcode-auth/
    ProxyPassReverse / http://linkedcode-auth/
</VirtualHost>
