name: granhermano

services:
  web:
    image: httpd:2.4
    container_name: granhermano-web
    restart: unless-stopped
    volumes:
      - /var/www/granhermano/www:/usr/local/apache2/htdocs
    networks:
      - projects_public

networks:
  projects_public:
    external: true
    name: projects_public
